name: Sync Fork

on:
  workflow_dispatch:
  schedule:
  - cron: "0 13 * * 1"

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Sync and merge upstream repository with your current repository
      uses: dabreadman/sync-upstream-repo@v1.3.0
      with:
        # URL of gitHub public upstream repo
        upstream_repo: https://github.com/csc301-2023-winter/6-John-T
        # Branch to merge from upstream (defaults to downstream branch)
        upstream_branch: main
        # Branch to merge into downstream
        downstream_branch: main
        # GitHub Bot token
        token: ${{ secrets.PAT_FOR_AUTO_SYNC_FORK }}
        # Git fetch arguments
#         fetch_args: # optional, default is 
        # Git merge arguments
#         merge_args: # optional, default is 
        # Git push arguments
#         push_args: # optional, default is 
        # Toggle to spawn `sync-upstream-repo` with time logs
#         spawn_logs: 
